package client.model;

public enum CommandType {
    NEW_MATCH_REQUEST_HUMAN,
    NEW_MATCH_RESPONSE_HUMAN,
    NEW_MATCH_REQUEST_COMPUTER,
    NEW_MATCH_RESPONSE_COMPUTER,
    WORD_REQUEST,
    WORD_RESPONSE,
    CONNECTED_WTH_SERVER,
    MATCH_START, WORD_BROADCAST
}

